# Docker Compose override for development
# This file is automatically loaded by docker-compose when present

version: '3.8'

services:
  prompt-library:
    build:
      target: builder  # Use builder stage for development
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for development
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - "3002:3000"
