version: '3.8'

services:
  prompt-library:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prompt-library-app
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - AUTH_EMAIL=${AUTH_EMAIL:-admin@promptlib.com}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-promptlib123}
    volumes:
      # Mount data directory for SQLite database persistence
      - ./data:/app/data
    networks:
      - prompt-library-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/prompts"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  prompt-library-network:
    driver: bridge

volumes:
  prompt-data:
    driver: local
